version: '3'
services:
  app:
    container_name: springboot-container
    image: 'stock_tracker:latest'
    ports:
      - "8080:8080"
    build: ./
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/stock_tracker
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      
  postgres:
    container_name: postgres-container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stock_tracker
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password